CREATE TABLE IF NOT EXISTS public.sms_gateway_devices (
  id UUID PRIMARY KEY,
  device_id VARCHAR(128) NOT NULL UNIQUE,
  fcm_token TEXT NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
